<a href="https://colab.research.google.com/github/HongYeongPyo/first-repository/blob/master/5%EB%A8%B8%EC%8B%A0_2%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0_3%EC%A0%84%EC%B2%98%EB%A6%AC_%EB%B2%94%EC%A3%BC%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-2 사이킷런 활용하기

## 데이터 불러오기

In [ ]:
# 데이터 생성
import pandas as pd
import numpy as np
data = pd.DataFrame({
    '메뉴': ['[인기]아이펠치킨','닭강정','간장치킨','마늘치킨','파닭','승일양념치킨','양념반후라이드반','황금후라이드','[베스트]풀잎치킨'],
    '가격': [16000,15000,14000,14000,14000,13000,13000,12000,9900],
    '호수' : [11,12,9,9,11,10,10,10,10],
    '칼로리' : [1200.0,1500.0,1600.0,1800.0,1300.0,1400.0,1300.0,1000.0,1000.0],
    '할인율' : [0.5,0.2,0.2,0.2,0.2,0.2,0.2,0.2,np.nan],
    '할인가' : [8000.0,12000.0,11200.0,11200.0,11200.0,10400.0,10400.0,9600.0,np.nan],
    '원산지' : ['국내산','브라질','국내산','국내산','브라질','국내산','국내산','국내산','국내산'],
    '살찔까요' : ['no','yes','yes','yes','yes','yes','yes','no','no'],
    '고민' : ['무조건먹자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','무조건먹자','무조건먹자']
})
data.to_csv('final_modudak.csv', index=False)
data

메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요     고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   no  무조건먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  yes   먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0  국내산  yes   먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  yes   먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  yes   먹지말자
5     승일양념치킨  13000  10  1400.0  0.2  10400.0  국내산  yes   먹지말자
6   양념반후라이드반  13000  10  1300.0  0.2  10400.0  국내산  yes   먹지말자
7     황금후라이드  12000  10  1000.0  0.2   9600.0  국내산   no  무조건먹자
8  [베스트]풀잎치킨   9900  10  1000.0  NaN      NaN  국내산   no  무조건먹자

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   메뉴      9 non-null      object 
 1   가격      9 non-null      int64  
 2   호수      9 non-null      int64  
 3   칼로리     9 non-null      float64
 4   할인율     8 non-null      float64
 5   할인가     8 non-null      float64
 6   원산지     9 non-null      object 
 7   살찔까요    9 non-null      object 
 8   고민      9 non-null      object 
dtypes: float64(3), int64(2), object(4)
memory usage: 780.0+ bytes


In [ ]:
data['원산지'].unique()

array(['국내산', '브라질'], dtype=object)

### 데이터 변경

In [ ]:
data.loc[2, '원산지'] = '미국'

In [ ]:
data['원산지'].unique()

array(['국내산', '브라질', '미국'], dtype=object)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   메뉴      9 non-null      object 
 1   가격      9 non-null      int64  
 2   호수      9 non-null      int64  
 3   칼로리     9 non-null      float64
 4   할인율     8 non-null      float64
 5   할인가     8 non-null      float64
 6   원산지     9 non-null      object 
 7   살찔까요    9 non-null      object 
 8   고민      9 non-null      object 
dtypes: float64(3), int64(2), object(4)
memory usage: 780.0+ bytes


## 활용할 데이터 선택

In [ ]:
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

# 2-3 데이터 전처리 : 범주형 데이터

## 2. 레이블 인코딩

- le.fit_transform(df['컬럼명']) *한번에 fit과 transform 변환

In [ ]:
# type 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   가격      9 non-null      int64  
 1   호수      9 non-null      int64  
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object 
 4   살찔까요    9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 492.0+ bytes


In [ ]:
print(df)   # 파일 내의 모든 데이터 보기

      가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no


In [ ]:
# 레이블(label) 인코딩

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(df['원산지'])
le.transform(df['원산지'])

#국내산 0, 브라질 2, 미국 1


array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [ ]:
# fit_transform
# fit과 transform를 한번에

le.fit_transform(df['원산지'])

array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [ ]:
# 데이터 변환

df['원산지'] = le.fit_transform(df['원산지'])
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0    0   no
1  15000  12  1500.0    2  yes
2  14000   9  1600.0    1  yes
3  14000   9  1800.0    0  yes
4  14000  11  1300.0    2  yes
5  13000  10  1400.0    0  yes
6  13000  10  1300.0    0  yes
7  12000  10  1000.0    0   no
8   9900  10  1000.0    0   no

In [ ]:
# '살찔까요'레이블 변환
le = LabelEncoder()      # 이 명령을 코딩하지 않아도 결과는 같았음.

df['살찔까요'] = le.fit_transform(df['살찔까요'])
df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

## 3. 여러 개의 column을 인코딩하는 경우

In [ ]:
# 활용할 데이터 선택 - 원본 데이터 불러오기

df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   가격      9 non-null      int64  
 1   호수      9 non-null      int64  
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object 
 4   살찔까요    9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 492.0+ bytes


In [ ]:
# 데이터가 object 타입인 column 선택 ['원산지', '살찔까요']

# 방법1
cols = ['원산지', '살찔까요']
cols

['원산지', '살찔까요']

In [ ]:
# 방법 2
cols = df.select_dtypes(include='object').columns
cols

Index(['원산지', '살찔까요'], dtype='object')

### for in 반복문

In [ ]:
# 한 번에 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

## 4. 원핫(one-hot) 인코딩

- 각 카테고리별로 컬럼을 만들어서 해당되는 카테고리의 컬럼은 1, 나머지 컬럼은 0으로 인코딩

In [ ]:
# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [ ]:
# 원핫인코딩
# 데이터프레임을 입력받기 때문에 대괄호를 2번 써야 합니다. (df[['원산지']])

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)
cat = ohe.fit_transform(df[['원산지']])
cat

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [ ]:
# 위에서 오류: sklearn 버젼 확인

import sklearn
print(sklearn.__version__)

1.6.1


In [ ]:
# 호환성을 위한 버전별 조건 처리

import sklearn
from sklearn.preprocessing import OneHotEncoder

if sklearn.__version__ >= '1.2':
    ohe = OneHotEncoder(sparse_output=False)
else:
    ohe = OneHotEncoder(sparse=False)

cat = ohe.fit_transform(df[['원산지']])
print(cat)


[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
# 피처(컬럼)이름과 카테고리

ohe.get_feature_names_out()

array(['원산지_국내산', '원산지_미국', '원산지_브라질'], dtype=object)

In [ ]:
# 데이터프레임으로 변환
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

원산지_국내산  원산지_미국  원산지_브라질
0      1.0     0.0      0.0
1      0.0     0.0      1.0
2      0.0     1.0      0.0
3      1.0     0.0      0.0
4      0.0     0.0      1.0
5      1.0     0.0      0.0
6      1.0     0.0      0.0
7      1.0     0.0      0.0
8      1.0     0.0      0.0

In [ ]:
# 데이터 프레임 합치기

df = pd.concat([df, df_cat], axis=1)
df

가격  호수     칼로리  원산지 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0  국내산   no      1.0     0.0      0.0
1  15000  12  1500.0  브라질  yes      0.0     0.0      1.0
2  14000   9  1600.0   미국  yes      0.0     1.0      0.0
3  14000   9  1800.0  국내산  yes      1.0     0.0      0.0
4  14000  11  1300.0  브라질  yes      0.0     0.0      1.0
5  13000  10  1400.0  국내산  yes      1.0     0.0      0.0
6  13000  10  1300.0  국내산  yes      1.0     0.0      0.0
7  12000  10  1000.0  국내산   no      1.0     0.0      0.0
8   9900  10  1000.0  국내산   no      1.0     0.0      0.0

In [ ]:
# 기존 컬럼 삭제

df = df.drop(['원산지'], axis = 1)
df


가격  호수     칼로리 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0   no      1.0     0.0      0.0
1  15000  12  1500.0  yes      0.0     0.0      1.0
2  14000   9  1600.0  yes      0.0     1.0      0.0
3  14000   9  1800.0  yes      1.0     0.0      0.0
4  14000  11  1300.0  yes      0.0     0.0      1.0
5  13000  10  1400.0  yes      1.0     0.0      0.0
6  13000  10  1300.0  yes      1.0     0.0      0.0
7  12000  10  1000.0   no      1.0     0.0      0.0
8   9900  10  1000.0   no      1.0     0.0      0.0

In [ ]:
# 활용 할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df


가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [ ]:
# 원핫인코딩

cols = df.select_dtypes(include = 'object').columns
ohe = OneHotEncoder(sparse = False)
cat = ohe.fit_transform(df[cols])

df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

## 위 코딩 버젼 오류 : 아이펠 LMS와 차이

In [ ]:
# 원핫인코딩

cols = df.select_dtypes(include = 'object').columns

#ohe = OneHotEncoder(sparse = False)
#======= sklearn 차이로 오류시 삽입 =======
import sklearn
from sklearn.preprocessing import OneHotEncoder

if sklearn.__version__ >= '1.2':
    ohe = OneHotEncoder(sparse_output=False)
else:
    ohe = OneHotEncoder(sparse=False)

#cat = ohe.fit_transform(df[['원산지']])
#print(cat)
#=======


cat = ohe.fit_transform(df[cols])

df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat





원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0      1.0     0.0      0.0      1.0       0.0
1      0.0     0.0      1.0      0.0       1.0
2      0.0     1.0      0.0      0.0       1.0
3      1.0     0.0      0.0      0.0       1.0
4      0.0     0.0      1.0      0.0       1.0
5      1.0     0.0      0.0      0.0       1.0
6      1.0     0.0      0.0      0.0       1.0
7      1.0     0.0      0.0      1.0       0.0
8      1.0     0.0      0.0      1.0       0.0

In [ ]:
#  데이터프레임 합치기

df = pd.concat([df, df_cat], axis=1)
df.head()

가격  호수     칼로리  원산지 살찔까요  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0  국내산   no      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0  브라질  yes      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0   미국  yes      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0  국내산  yes      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0  브라질  yes      0.0     0.0      1.0      0.0       1.0

In [ ]:
# 컬럼 삭제

df=df.drop(cols, axis = 1)
df

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0      0.0     0.0      1.0      0.0       1.0
5  13000  10  1400.0      1.0     0.0      0.0      0.0       1.0
6  13000  10  1300.0      1.0     0.0      0.0      0.0       1.0
7  12000  10  1000.0      1.0     0.0      0.0      1.0       0.0
8   9900  10  1000.0      1.0     0.0      0.0      1.0       0.0

## 원핫인 코딩 : 판다스 활용
- 두 개의 파일에서 커럼 수가 다를 경우에는 판다스를 활용하지 못함
- 한 개의 파일은 컬럼이 2개, 다른 한 개 파일은 3개인 경우 두 개의 모두 컬럼 수가 많은 컬럼 수로 처리함
- 이 경우에는 사이킷런으로 해야 함

In [ ]:
# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df.head()

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes

In [ ]:
# 판다스를 활한 원핫 인코딩

df = pd.get_dummies(df)
df

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0     True   False    False     True     False
1  15000  12  1500.0    False   False     True    False      True
2  14000   9  1600.0    False    True    False    False      True
3  14000   9  1800.0     True   False    False    False      True
4  14000  11  1300.0    False   False     True    False      True
5  13000  10  1400.0     True   False    False    False      True
6  13000  10  1300.0     True   False    False    False      True
7  12000  10  1000.0     True   False    False     True     False
8   9900  10  1000.0     True   False    False     True     False