<a href="https://colab.research.google.com/github/HongYeongPyo/first-repository/blob/master/5%EB%A8%B8t%EC%8B%A0_2%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0_4%EC%A0%84%EC%B2%98%EB%A6%AC_%EC%88%98%EC%B9%98%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-4 데이터 전처리 : 수치형


In [20]:
# 데이터 생성
import pandas as pd
import numpy as np
data = pd.DataFrame({
    '메뉴': ['[인기]아이펠치킨','닭강정','간장치킨','마늘치킨','파닭','승일양념치킨','양념반후라이드반','황금후라이드','[베스트]풀잎치킨'],
    '가격': [16000,15000,14000,14000,14000,13000,13000,12000,9900],
    '호수' : [11,12,9,9,11,10,10,10,10],
    '칼로리' : [1200.0,1500.0,1600.0,1800.0,1300.0,1400.0,1300.0,1000.0,1000.0],
    '할인율' : [0.5,0.2,0.2,0.2,0.2,0.2,0.2,0.2,np.nan],
    '할인가' : [8000.0,12000.0,11200.0,11200.0,11200.0,10400.0,10400.0,9600.0,np.nan],
    '원산지' : ['국내산','브라질','국내산','국내산','브라질','국내산','국내산','국내산','국내산'],
    '살찔까요' : ['no','yes','yes','yes','yes','yes','yes','no','no'],
    '고민' : ['무조건먹자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','무조건먹자','무조건먹자']
})
data.to_csv('final_modudak.csv', index=False)
data

메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요     고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   no  무조건먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  yes   먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0  국내산  yes   먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  yes   먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  yes   먹지말자
5     승일양념치킨  13000  10  1400.0  0.2  10400.0  국내산  yes   먹지말자
6   양념반후라이드반  13000  10  1300.0  0.2  10400.0  국내산  yes   먹지말자
7     황금후라이드  12000  10  1000.0  0.2   9600.0  국내산   no  무조건먹자
8  [베스트]풀잎치킨   9900  10  1000.0  NaN      NaN  국내산   no  무조건먹자

In [21]:
# 데이터 변경
data.loc[2,'원산지'] = '미국'

In [22]:
# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [23]:

# 한 번에 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [24]:
# 호환성을 위한 버전별 조건 처리

import sklearn
from sklearn.preprocessing import OneHotEncoder

if sklearn.__version__ >= '1.2':
    ohe = OneHotEncoder(sparse_output=False)
else:
    ohe = OneHotEncoder(sparse=False)

cat = ohe.fit_transform(df[['원산지']])
print(cat)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [27]:

# 피처(컬럼)이름과 카테고리

ohe.get_feature_names_out()

array(['원산지_0', '원산지_1', '원산지_2'], dtype=object)

In [28]:
# 방법 2
cols = df.select_dtypes(include='object').columns
cols

Index([], dtype='object')

In [30]:
# 데이터프레임으로 변환
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out(), dtype=int)
df_cat

원산지_0  원산지_1  원산지_2
0      1      0      0
1      0      0      1
2      0      1      0
3      1      0      0
4      0      0      1
5      1      0      0
6      1      0      0
7      1      0      0
8      1      0      0

In [31]:
# 데이터 프레임 합치기

df = pd.concat([df, df_cat], axis=1)
df

가격  호수     칼로리  원산지  살찔까요  원산지_0  원산지_1  원산지_2
0  16000  11  1200.0    0     0      1      0      0
1  15000  12  1500.0    2     1      0      0      1
2  14000   9  1600.0    1     1      0      1      0
3  14000   9  1800.0    0     1      1      0      0
4  14000  11  1300.0    2     1      0      0      1
5  13000  10  1400.0    0     1      1      0      0
6  13000  10  1300.0    0     1      1      0      0
7  12000  10  1000.0    0     0      1      0      0
8   9900  10  1000.0    0     0      1      0      0

In [32]:
# 기존 컬럼 삭제

df = df.drop(['원산지'], axis = 1)
df


가격  호수     칼로리  살찔까요  원산지_0  원산지_1  원산지_2
0  16000  11  1200.0     0      1      0      0
1  15000  12  1500.0     1      0      0      1
2  14000   9  1600.0     1      0      1      0
3  14000   9  1800.0     1      1      0      0
4  14000  11  1300.0     1      0      0      1
5  13000  10  1400.0     1      1      0      0
6  13000  10  1300.0     1      1      0      0
7  12000  10  1000.0     0      1      0      0
8   9900  10  1000.0     0      1      0      0

In [33]:
# StandsrdScaler (표준화)

from sklearn.preprocessing  import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(df[['가격']])

array([[ 1.54246993],
       [ 0.94150762],
       [ 0.34054531],
       [ 0.34054531],
       [ 0.34054531],
       [-0.260417  ],
       [-0.260417  ],
       [-0.86137931],
       [-2.12340016]])

In [34]:
# StandsrdScaler 여러 변수에 적용

cols = ['가격', '호수', '칼로리']
scaler = StandardScaler()
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수       칼로리  살찔까요  원산지_0  원산지_1  원산지_2
0  1.542470  0.848875 -0.577920     0      1      0      0
1  0.941508  1.940285  0.622376     1      0      0      1
2  0.340545 -1.333946  1.022475     1      0      1      0
3  0.340545 -1.333946  1.822672     1      1      0      0
4  0.340545  0.848875 -0.177822     1      0      0      1
5 -0.260417 -0.242536  0.222277     1      1      0      0
6 -0.260417 -0.242536 -0.177822     1      1      0      0
7 -0.861379 -0.242536 -1.378118     0      1      0      0
8 -2.123400 -0.242536 -1.378118     0      1      0      0

## 2. 정규화

In [36]:
# MinMaxScaler(정규화)

from sklearn.preprocessing import  MinMaxScaler
cols = ['가격', '호수', '칼로리']
scaler = MinMaxScaler()
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수    칼로리  살찔까요  원산지_0  원산지_1  원산지_2
0  1.000000  0.666667  0.250     0      1      0      0
1  0.836066  1.000000  0.625     1      0      0      1
2  0.672131  0.000000  0.750     1      0      1      0
3  0.672131  0.000000  1.000     1      1      0      0
4  0.672131  0.666667  0.375     1      0      0      1
5  0.508197  0.333333  0.500     1      1      0      0
6  0.508197  0.333333  0.375     1      1      0      0
7  0.344262  0.333333  0.000     0      1      0      0
8  0.000000  0.333333  0.000     0      1      0      0